version: 2.1
jobs:
  Initial-setup:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Initial message
          command: |
            echo 'Continuos delivery and integration masterclass'
            echo 'Starting pipeline'
  Fetch-code:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - checkout
      - run:
          name: Getting the code
          command: |
            echo 'Repository files from Develop branch'
            ls -la
  Check-python-version:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Get Python Version
          command: |
            python3 --version
  Check-flask-version:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Get Flask Version
          command: |
            echo 'Get Flask version from app'
  Run-unit-test:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - checkout
      - run:
          name: Run unit test
          command: |
            echo 'Running unit test'
  Run-automation-test:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Run automation test
          command: |
            echo 'Running automation test'
  Create-temp-instance:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Create Temp Instance to Automation test
          command: |
            echo 'Creating temp instance'
  Notification-test-environment-updated:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - checkout
      - run:
          name: Send notification to team
          command: |
            echo 'Sending notification to team'
  Change-ticket-to-qa:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - checkout
      - run:
          name: Change Ticket to QA
          command: |
            echo 'Passing ticket to QA'
  Update-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Create new Imagen version
          command: |
            ls -la
            cd Integracion
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker build -t estebanbs/integracion-test:latest .
            docker push estebanbs/integracion-test:latest
workflows:
  Pipeline-workflow:
    jobs:
      - Initial-setup
      - Fetch-code:
          requires:
            - Initial-setup
      - Check-python-version:
          requires:
            - Fetch-code
      - Check-flask-version:
          requires:
            - Check-python-version
      - Run-unit-test:
          requires:
            - Check-flask-version
      - Create-temp-instance:
          requires:
            - Check-flask-version
      - Run-automation-test:
          requires:
            - Create-temp-instance
      - Update-image:
          requires:
            - Run-unit-test
            - Run-automation-test
      - Change-ticket-to-qa:
          requires:
            - Update-image
      - Notification-test-environment-updated:
          requires:
            - Update-image