version: 2.1
jobs:
  Initial-setup:
    docker:
      - image: alopezgsource/login_integracion:1.2
    steps:
      - run:
          name: Initial message
          command: |
            echo 'Continuos delivery and integration masterclass'
            echo 'Starting pipeline'
  Fetch-code:
    docker:
      - image: alopezgsource/login_integracion:1.2
    steps:
      - checkout
      - run:
          name: Getting the code
          command: |
            Repository files from Develop branch
            ls -la
  Get-python-version:
    docker:
      - image: alpine:3.17
    steps:
      - run:
          name: Get Python Version
          command: |
            python -v
workflows:
  Pipeline-workflow:
    jobs:
      - Initial-setup
      - Fetch-Code:
          requires:
            - Initial-setup
      - Get-python-version:
          requires:
            - Fetch-Code