version: 2.1
jobs:
  Initial-setup:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Initial message
          command: |
            echo 'Continuos delivery and integration masterclass'
            echo 'Starting pipeline'
  Fetch-code:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - checkout
      - run:
          name: Getting the code
          command: |
            echo 'Repository files from Develop branch'
            ls -la
  Get-python-version:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Get Python Version
          command: |
            python3 --version
  Update-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Create new Imagen version
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker build -t estebanbs/integracion-test:1.0.1 .
            docker push estebanbs/integracion-test:latest
workflows:
  Pipeline-workflow:
    jobs:
      - Initial-setup
      - Fetch-code:
          requires:
            - Initial-setup
      - Get-python-version:
          requires:
            - Fetch-code
      - Update-image:
          requires:
            - Fetch-code