version: 2.1
jobs:
  Initial-setup:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Initial message
          command: |
            echo 'Continuos delivery and integration masterclass'
            echo 'Starting pipeline'
  Fetch-code:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - checkout
      - run:
          name: Getting the code
          command: |
            echo 'Repository files from Develop branch'
            ls -la
  Get-python-version:
    docker:
      - image: estebanbs/integracion-test:1.0.0
    steps:
      - run:
          name: Get Python Version
          command: |
            python3 --version
  Update-image:
    docker:
      - image: docker:latest
    steps:
      - run:
          name: Create Imagen version
          command: |
            ls -la
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
workflows:
  Pipeline-workflow:
    jobs:
      - Initial-setup
      - Fetch-code:
          requires:
            - Initial-setup
      - Get-python-version:
          requires:
            - Fetch-code
      - Update-image:
          requires:
            - Fetch-code